"""Freeze a submission together with the exact code that produced it.

A CSV without its source is unreproducible, and a source tree that keeps moving
underneath a sealed CSV is worse than useless -- it looks authoritative while
describing something else. This captures both at one instant and records a
SHA256 for every file, so any later drift is detectable rather than assumed
absent.

    python -m scripts.seal_submission --score 77.3904 --csv submission_w050.csv \
        --command "python -m scripts.generate_submission ..."
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
from datetime import datetime
from pathlib import Path

SOURCE_DIRS = ("hangman", "scripts", "gpu_experiment")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--score", required=True)
    ap.add_argument("--csv", type=Path, required=True)
    ap.add_argument("--notebook", type=Path, default=Path("submission_notebook.ipynb"))
    ap.add_argument("--checkpoint", type=Path,
                    default=Path("artifacts/run6/best_model.pt"))
    ap.add_argument("--command", default="", help="exact command that made the CSV")
    ap.add_argument("--note", default="")
    args = ap.parse_args()

    rows = sum(1 for _ in args.csv.open(encoding="utf-8"))
    if rows != 250_001:
        raise SystemExit(f"REFUSING to seal: {args.csv} has {rows:,} lines, expected 250,001")

    out = Path(f"FINAL_{args.score}")
    out.mkdir(exist_ok=True)
    shutil.copy(args.csv, out / "submission.csv")
    shutil.copy(args.notebook, out / "submission_notebook.ipynb")
    shutil.copy(args.checkpoint, out / "run6_best_model.pt")

    code = out / "code_snapshot"
    if code.exists():
        shutil.rmtree(code)
    for d in SOURCE_DIRS:
        src = Path(d)
        if src.is_dir():
            shutil.copytree(src, code / d,
                            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))

    lines = [
        f"SUBMISSION SEAL  --  {args.score}%",
        f"sealed: {datetime.now():%Y-%m-%d %H:%M:%S}",
        f"rows:   {rows:,}",
        "",
        "Generated by:",
        f"  {args.command or '(not recorded)'}",
    ]
    if args.note:
        lines += ["", "Note:", f"  {args.note}"]
    lines += ["", "ARTEFACTS", "-" * 72]
    for f in sorted(out.glob("*")):
        if f.is_file() and f.name != "MANIFEST.txt":
            lines.append(f"{sha256(f)[:32]}  {f.name}  ({f.stat().st_size:,} bytes)")

    lines += ["", "SOURCE SNAPSHOT", "-" * 72]
    n = 0
    for f in sorted(code.rglob("*.py")):
        lines.append(f"{sha256(f)[:32]}  {f.relative_to(code).as_posix()}")
        n += 1
    lines += ["", f"{n} source files captured."]

    (out / "MANIFEST.txt").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines[:12]))
    print(f"\n... {n} source files hashed")
    print(f"sealed -> {out}")


if __name__ == "__main__":
    main()
